name: prospie
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - acres==0.5.0
    - annotated-types==0.7.0
    - anthropic==0.72.0
    - anyio==4.9.0
    - appnope==0.1.4
    - asttokens==3.0.0
    - beautifulsoup4==4.13.4
    - Bottleneck==1.4.2
    - Brotli==1.0.9
    - brotlicffi==1.0.9.2
    - certifi==2025.8.3
    - cffi==2.0.0
    - charset-normalizer==3.3.2
    - ci-info==0.3.0
    - click==8.1.8
    - comm==0.2.1
    - configobj==5.0.9
    - configparser==7.2.0
    - contourpy==1.3.1
    - cryptography==46.0.2
    - cycler==0.11.0
    - debugpy==1.8.11
    - decorator==5.1.1
    - Deprecated==1.2.18
    - deprecation==2.1.0
    - distro==1.9.0
    - docstring_parser==0.17.0
    - etelemetry==0.3.1
    - exceptiongroup==1.2.0
    - executing==0.8.3
    - filelock==3.20.0
    - fitz==0.0.1.dev2
    - fonttools==4.55.3
    - git-filter-repo==2.47.0
    - gotrue==2.12.3
    - h11==0.16.0
    - h2==4.2.0
    - hpack==4.1.0
    - httpcore==1.0.9
    - httplib2==0.31.0
    - httpx==0.28.1
    - hyperframe==6.1.0
    - idna==3.7
    - img2pdf==0.6.1
    - importlib_resources==6.5.2
    - ipykernel==6.29.5
    - ipython==8.30.0
    - isodate==0.7.2
    - jedi==0.19.2
    - jiter==0.11.1
    - joblib==1.4.2
    - jupyter_client==8.6.3
    - jupyter_core==5.8.1
    - kiwisolver==1.4.8
    - looseversion==1.3.0
    - lxml==6.0.2
    - markdown-it-py==4.0.0
    - matplotlib==3.10.0
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - multipledispatch==0.6.0
    - natsort==8.4.0
    - nest-asyncio==1.6.0
    - networkx==3.4.2
    - nibabel==5.3.2
    - nipype==1.10.0
    - numexpr==2.10.1
    - numpy<2
    - ocrmypdf==16.11.1
    - packaging==24.2
    - pandas==2.2.3
    - pandas_flavor==0.7.0
    - parso==0.8.4
    - pathlib==1.0.1
    - pdfminer.six==20250506
    - pdfplumber==0.11.7
    - pexpect==4.9.0
    - pi_heif==1.1.1
    - pikepdf==10.0.0
    - pillow==11.1.0
    - platformdirs==4.3.7
    - pluggy==1.6.0
    - postgrest==1.1.1
    - prompt-toolkit==3.0.43
    - prov==2.1.1
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - puremagic==1.30
    - pycparser==2.21
    - pycryptodome==3.23.0
    - pydantic==2.11.7
    - pydantic_core==2.33.2
    - pydot==4.0.1
    - Pygments==2.19.1
    - pyjanitor==0.31.0
    - PyJWT==2.10.1
    - PyMuPDF==1.26.5
    - pyparsing==3.2.0
    - PyPDF2==3.0.1
    - pypdfium2==4.30.0
    - PySocks==1.7.1
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.1.0
    - pytz==2024.1
    - pyxnat==1.6.3
    - pyzmq==26.2.0
    - rdflib==7.3.0
    - realtime==2.5.3
    - requests==2.32.4
    - rich==14.2.0
    - scikit-learn==1.6.1
    - scipy==1.15.3
    - seaborn==0.13.2
    - simplejson==3.20.2
    - six==1.17.0
    - sniffio==1.3.1
    - soupsieve==2.5
    - stack-data==0.2.0
    - storage3==0.12.0
    - StrEnum==0.4.15
    - supabase==2.16.0
    - supafunc==0.10.1
    - threadpoolctl==3.5.0
    - tornado==6.5.1
    - traitlets==5.14.3
    - traits==7.0.2
    - typing-inspection==0.4.1
    - typing_extensions==4.14.1
    - tzdata==2025.2
    - unicodedata2==15.1.0
    - urllib3==2.5.0
    - wcwidth==0.2.13
    - websockets==15.0.1
    - wrapt==1.17.3
    - xarray==2025.4.0
    - xlrd==2.0.1
